### PR TITLE
update 2.7.10a_alpha_220601

### PR DESCRIPTION
**Pull request by asmariyaz23**
- Update Starsolo 2.7.10a_alpha_220601

### CODE REVIEW

**Comment by yihming** [comment]
@asmariyaz23 Please directly modify `2.7.10a/Dockerfile`.

**Review by yihming — CHANGES_REQUESTED** [review]
Please directly modify `2.7.10a/Dockerfile`.

**Comment by asmariyaz23** [comment]
@yihming I have done this

**Comment by yihming** [comment]
@asmariyaz23 Two more things:
- In "workflows/starsolo/starsolo_workflow.wdl", change default `star_version` from "2.7.9a" to "2.7.10a".
- In "docs/starsolo.rst", update the corresponding table row (i.e. Line 312 - 315). Moreover, change the link of 2.7.10a from `2.7.10a_alpha_220506` to `2.7.10a_alpha_220601` (link https://github.com/alexdobin/STAR/releases/tag/2.7.10a_alpha_220601).

**Review by yihming — CHANGES_REQUESTED** [review]
Please resolve my two new comments above. Thanks!

**Comment by asmariyaz23** [comment]
@yihming this is done.

**Pull request merged**
