### PR TITLE
Change default platform to x86_64

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by yihming** [comment]
@joshua-gould Just curious: may I know the difference between `amd64` and `x86_64`?

**Comment by joshua-gould** [comment]
Please see https://askubuntu.com/questions/601553/what-is-the-difference-between-x86-64-amd64-and-64-bit#:~:text=x86_64%20is%20name%20of%20specific,released%20by%20Intel%20in%201999).

**Comment by yihming** [comment]
Sorry, I don't quite get it. I've just done a little bit search, and it seems that `amd64` and `x86_64` are aliases referring to the same platform. And on Docker Hub, it just shows `linux/amd64` for this platform (see the screen shot attached):

Screen Shot 2022-08-23 at 15 12 43

**Comment by joshua-gould** [comment]
Ah, my mistake. It looks like they are synonyms.

**Pull request closed without merging**
